import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { authenticate, registerUser } from '../data/mockDb';
import { useShop } from '../context/ShopContext';
export default function Auth({ mode }) {
  const registering = mode === 'register'; const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const { login } = useShop(); const navigate = useNavigate();
  const submit = (event) => { event.preventDefault(); setError(''); try { const user = registering ? registerUser(form) : authenticate(form.email, form.password); login(user); navigate(user.role === 'admin' ? '/admin' : '/'); } catch (err) { setError(err.message); } };
  return <main className="auth-page d-flex align-items-center py-5"><section className="auth-card card border-0 shadow mx-auto"><div className="card-body p-4 p-md-5"><Link className="text-decoration-none text-success" to="/">← Volver a la tienda</Link><h1 className="serif mt-4">{registering ? 'Crear una cuenta' : 'Bienvenido nuevamente'}</h1><p className="text-secondary">{registering ? 'Regístrate para agilizar tus compras.' : 'Ingresa a Veterinaria San Marcos.'}</p>{error && <div className="alert alert-danger" role="alert">{error}</div>}<form onSubmit={submit} className="mt-4">{registering && <div className="mb-3"><label className="form-label">Nombre completo</label><input required className="form-control" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></div>}<div className="mb-3"><label className="form-label">Correo electrónico</label><input required type="email" className="form-control" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></div><div className="mb-3"><label className="form-label">Contraseña</label><input required minLength="6" type="password" className="form-control" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></div><button className="btn btn-success w-100">{registering ? 'Crear cuenta' : 'Iniciar sesión'}</button></form><p className="text-center small mt-4">{registering ? '¿Ya tienes cuenta?' : '¿Aún no tienes cuenta?'} <Link to={registering ? '/ingresar' : '/registro'}>{registering ? 'Inicia sesión' : 'Regístrate'}</Link></p>{!registering && <p className="text-secondary small mb-0">Demo administrador: admin@sanmarcos.cl / Admin123!</p>}</div></section></main>;
}
