import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useShop } from '../context/ShopContext';
import { createOrder } from '../data/mockDb';
import { formatMoney } from '../components/ProductCard';
export default function Checkout() {
  const { cart, cartTotal, setCart, user } = useShop(); const navigate = useNavigate(); const [error, setError] = useState(''); const [form, setForm] = useState({ name: user?.name || '', email: user?.email || '', address: '', delivery: 'Despacho a domicilio', payment: 'Tarjeta de débito' });
  const change = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = (event) => { event.preventDefault(); if (!cart.length) return navigate('/carrito'); try { const order = createOrder({ customer: form, items: cart, total: cartTotal }); setCart([]); navigate('/resultado/exito', { state: { order } }); } catch (err) { setError(err.message); } };
  return <section className="container py-5"><h1 className="serif">Checkout</h1><p className="text-secondary">Completa tus datos de entrega. Si iniciaste sesión, algunos campos ya están listos.</p><div className="row g-4"><form className="col-lg-8" onSubmit={submit}><div className="card border-0 shadow-sm"><div className="card-body p-4"><h2 className="h5">Datos de envío</h2>{error && <div className="alert alert-danger">{error}</div>}<div className="row g-3"><div className="col-md-6"><label className="form-label">Nombre completo</label><input required name="name" className="form-control" value={form.name} onChange={change} /></div><div className="col-md-6"><label className="form-label">Correo</label><input required type="email" name="email" className="form-control" value={form.email} onChange={change} /></div><div className="col-12"><label className="form-label">Dirección</label><input required name="address" className="form-control" placeholder="Calle, número, comuna" value={form.address} onChange={change} /></div><div className="col-md-6"><label className="form-label">Entrega</label><select name="delivery" className="form-select" value={form.delivery} onChange={change}><option>Despacho a domicilio</option><option>Retiro en veterinaria</option></select></div><div className="col-md-6"><label className="form-label">Medio de pago</label><select name="payment" className="form-select" value={form.payment} onChange={change}><option>Tarjeta de débito</option><option>Tarjeta de crédito</option><option>Transferencia</option></select></div></div><button className="btn btn-success mt-4" type="submit">Confirmar compra</button></div></div></form><aside className="col-lg-4"><div className="card border-0 shadow-sm"><div className="card-body"><h2 className="h5">Resumen</h2>{cart.map((item) => <div className="d-flex justify-content-between small mb-2" key={item.id}><span>{item.quantity} × {item.name}</span><span>{formatMoney(item.quantity * item.price)}</span></div>)}<div className="d-flex justify-content-between border-top pt-3 mt-3"><strong>Total</strong><strong>{formatMoney(cartTotal)}</strong></div></div></div></aside></div></section>;
}
